#!/usr/bin/env ruby

site 'https://supermarket.getchef.com/api/v1'

cookbook 'sprout-chruby',
  :github => 'pivotal-sprout/sprout-chruby'

cookbook 'sprout-ruby',
  :github => 'pivotal-sprout/sprout-ruby'

cookbook 'sprout-mysql',
  :github => 'pivotal-sprout/sprout-mysql'

cookbook 'sprout-git',
  :github => 'pivotal-sprout/sprout-git'

cookbook 'sprout-base',
  :github => 'pivotal-sprout/sprout-base'

cookbook 'sprout-osx-apps',
  :github => 'pivotal-sprout/sprout-osx-apps'

cookbook 'sprout-osx-settings',
  :github => 'pivotal-sprout/sprout-osx-settings'

cookbook 'osx',
  :github => 'pivotal-sprout/osx'

cookbook 'sprout-jetbrains-editors',
  :github => 'pivotal-sprout/sprout-jetbrains-editors'

cookbook 'sprout-homebrew',
  :github => 'pivotal-sprout/sprout-homebrew'

cookbook 'sprout-postgresql',
  :github => 'pivotal-sprout/sprout-postgresql'

cookbook 'sprout-ssh',
  :github => 'pivotal-sprout/sprout-ssh'

cookbook 'homebrew'

cookbook 'capi', path: 'capi'
