include_recipe 'capi::acceptance_tests'
include_recipe 'capi::bosh_directors'
include_recipe 'capi::concourse_cli'
include_recipe 'capi::spiff'
include_recipe 'capi::vim_luan'
include_recipe 'capi::atom'
include_recipe 'capi::checkman'
