include_recipe 'capi::acceptance_tests'
include_recipe 'capi::bosh_directors'
include_recipe 'capi::concourse_cli'
include_recipe 'capi::ctags'
include_recipe 'capi::fast_bosh'
include_recipe 'capi::fzf'
include_recipe 'capi::vim'
