include_recipe 'capi::acceptance_tests'
include_recipe 'capi::bosh_directors'
include_recipe 'capi::concourse_cli'
include_recipe 'capi::fast_bosh'
include_recipe 'capi::vim'
include_recipe 'capi::vim_luan'
